export enum ProblemDefinitionQuadrant {
  MAIN_QUESTION = 'MAIN_QUESTION',
  TARGET_AUDIENCE = 'TARGET_AUDIENCE',
  CONSEQUENCES = 'CONSEQUENCES',
  ALTERNATIVE_VIEW = 'ALTERNATIVE_VIEW',
  SOCIAL_FACTORS = 'SOCIAL_FACTORS',
  PROBLEM_DEFINITION = 'PROBLEM_DEFINITION',
}
