export enum VoteableEntityType {
  EMPATHY_MAP = 'EMPATHY_MAP',
  EMPATHY_MAP_RESPONSE = 'EMPATHY_MAP_RESPONSE',
  CHALLENGE_DEFINITION_RESPONSE = 'CHALLENGE_DEFINITION_RESPONSE',
  PROBLEM_DEFINITION_RESPONSE = 'PROBLEM_DEFINITION_RESPONSE',
}
