services:
  postgres_dtep:
    image: postgres:latest
    container_name: postgres_dtep
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dtep
      POSTGRES_PASSWORD: dtep
      POSTGRES_DB: dtep
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
